### ISSUE TITLE
Communicate With Buildifier Through DLLs

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#89]
# Communicate With Buildifier Through DLLs

If the speed becomes a problem with communicating with the buildifier through stdin/stdout, or, more likel, if we want to package the buildifier with the server, we should use DLLs instead. The buildifier is written in go, so we can do this.

This will remove the need for #76 

## Tasks

- [ ] Import the golang libraries into the WORKSPACE
- [ ] Create a golang buildifier wrapper within the `server/src/main/go` directory
- [ ] Export and link those go rules using dynamic libraries with the BUILD system
- [ ] Update the `server.buildifier` package to use the dynamic libraries instead
