### ISSUE TITLE
API For Querying Bazel Projects

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#93]
Create an API for querying Bazel projects using the WORKSPACE tree domain developed by @NovaMachina. Ideally this API would be a "chained" API for simplicity. E.g.

```
List<BuildTarget> targets = WorkspaceTree("@myrepo").findBuildTargets("/path/to/package").findDeps(...);
List<BuildFile> packages = WorkspaceTree("@another_repo").findPackages("/path/to/");
var something = WorkspaceTree(...).find(...).find(...).find(...); // Just this general structure
```

But do what you think is most appropriate. This is going to be used in many of our providers.

- [x] Create easy to use API

Query features we need:

- [x] Search a WORKSPACE tree for possible completions for a *path*. Given "//path/to/", return "//path/to/a", "//path/to/b".  This will be used for autocompletion #7.
- [x] Search a WORKSPACE tree for possible targets for a *package*. Given "//path/to:", return "//path/to:targetA", "//path/to:targetB". This will be used for autocompletion #7.
- [x] Determine if a path is a valid *target*. Given "//path/to:targetA", return whether target exists. This will be used for semantic highlighting, #58.
- [x] Determine the source files associated with a build target. Given "path/to/source/file.java", return the BazelTarget which uses that source file. This will be used for src to build navigation #86.
- [x] Feel free to add any more queries you feel are necessary.
Added
- [x] Determine if a givenSourcePath is a valid *file*. Given "//path/to/file.java", return whether the file exists. 

Unit tests

- [x] Create unit tests to test the queries.

**Comment by josiahsrc** [comment]
More context found in #82
